sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 8.1
    - php: 8.2

before_install:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - if [ "$PACKAGES" != "" ]; then composer require --no-update $PACKAGES; fi
  - composer update $COMPOSER_OPTIONS

script:
  - vendor/bin/phpspec run
